"""add raw offers table

Revision ID: 2c83d41a00b6
Revises: b96c6b69ebef
Create Date: 2026-05-04 19:55:56.602214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c83d41a00b6'
down_revision: Union[str, Sequence[str], None] = 'b96c6b69ebef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('store', sa.String(length=100), nullable=False),
    sa.Column('normalized_title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('positive_percent', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('genres', sa.Text(), nullable=True),
    sa.Column('price_original', sa.Integer(), nullable=True),
    sa.Column('price_discount', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.String(length=4), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'store', name='uq_raw_offer_store')
    )
    op.add_column('games', sa.Column('normalized_title', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'games', ['normalized_title'])
    op.create_unique_constraint('uq_game_store', 'offers', ['title', 'store_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_game_store', 'offers', type_='unique')
    op.drop_constraint(None, 'games', type_='unique')
    op.drop_column('games', 'normalized_title')
    op.drop_table('raw_offers')
    # ### end Alembic commands ###
