"""refactor offers raw fields

Revision ID: 33dc50656bf7
Revises: f75d45e7f1fc
Create Date: 2026-04-25 17:48:38.534606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33dc50656bf7'
down_revision: Union[str, Sequence[str], None] = 'f75d45e7f1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('developer', sa.String(length=255), nullable=True))
    op.add_column('offers', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('offers', sa.Column('platforms', sa.Text(), nullable=True))
    op.add_column('offers', sa.Column('genres', sa.Text(), nullable=True))
    op.drop_constraint(op.f('offers_platform_id_fkey'), 'offers', type_='foreignkey')
    op.drop_constraint(op.f('offers_developer_id_fkey'), 'offers', type_='foreignkey')
    op.drop_constraint(op.f('offers_publisher_id_fkey'), 'offers', type_='foreignkey')
    op.drop_column('offers', 'publisher_id')
    op.drop_column('offers', 'developer_id')
    op.drop_column('offers', 'platform_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('developer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('offers', sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('offers_publisher_id_fkey'), 'offers', 'publishers', ['publisher_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('offers_developer_id_fkey'), 'offers', 'developers', ['developer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('offers_platform_id_fkey'), 'offers', 'platforms', ['platform_id'], ['id'], ondelete='SET NULL')
    op.drop_column('offers', 'genres')
    op.drop_column('offers', 'platforms')
    op.drop_column('offers', 'publisher')
    op.drop_column('offers', 'developer')
    # ### end Alembic commands ###
