"""empty message

Revision ID: b96c6b69ebef
Revises: 33dc50656bf7
Create Date: 2026-05-04 17:25:10.522442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96c6b69ebef'
down_revision: Union[str, Sequence[str], None] = '33dc50656bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('normalized_title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'normalized_title')
    # ### end Alembic commands ###
