"""add birthdate and created_at to UserOrm

Revision ID: e6e3f006e087
Revises: 2d800847c045
Create Date: 2026-03-30 17:22:11.544706

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6e3f006e087'
down_revision: Union[str, Sequence[str], None] = '2d800847c045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
